### ISSUE TITLE
Serenity-cucumberjvm: Steps grid in serenity report does not display data when tests for the data in Examples fail

### ISSUE THREAD

**Issue by RamnathRaghu** [serenity-bdd/serenity-cucumber#101]
Srenenity-cucumberjvm: Steps grid in serenity report does not display data when tests for the data in Examples fail.
![image](https://user-images.githubusercontent.com/28475399/32472175-62d2b742-c3b5-11e7-9023-ab600914d606.png)

**Comment by wakaleo** [comment]
What version are you using?

**Comment by RamnathRaghu** [comment]
Hi John,

Please find below the version used.
<serenity.version>1.6.6</serenity.version>
<serenity.cucumber.version>1.5.15</serenity.cucumber.version>

**Comment by wakaleo** [comment]
Could you check with the latest versions? (1.7.0 and 1.6.3)?

**Comment by RamnathRaghu** [comment]
Sure. I will come back with the outcome soon.

**Comment by RamnathRaghu** [comment]
Hi John,

After using the latest versions of jars, the behavior is still the same.

**Comment by wakaleo** [comment]
I haven't been able to reproduce this at all, could you provide a sample project?

**Comment by RamnathRaghu** [comment]
Hi John,

I am successfully able to reproduce with the latest version of serenity jars. I am attaching a sample project for you investigation. The same project can be used for issue #100 

[sample.zip](https://github.com/serenity-bdd/serenity-cucumber/files/1452088/sample.zip)

**Comment by RamnathRaghu** [comment]
This behaviour is the same for an ERROR outcome as well.

**Comment by rraghuna** [comment]
Many thanks, John for taking time to fix this. I have tested this with the latest jars and the issue has been fixed.

**Comment by wakaleo** [comment]
Thanks for the update.
