### ISSUE TITLE
Serenity Report : The placeholder (column) values in the second Examples table of a scenario is all mixed-up

### ISSUE THREAD

**Issue by rraghuna** [serenity-bdd/serenity-cucumber#105]
**Description**:

The placeholder values in the second Examples table of a scenario is all mixed-up

**Steps to Reproduce**:

1) Write a Gherkin scenario outline with Examples split into two like in the below example
2)  Run the test from maven (mvn clean verify) and check the report

**Expected Results**:

The column title in the examples table for a scenario should match with its values.

**Actual**:

When there are more than 1 examples sets present for a scenario, the column values of the second or subsequent examples tables in the serenity report are all mixed-up and not as per the Gherkin scenario examples table.

**Environment:**

<serenity.version>1.8.1</serenity.version>
<serenity.maven.version>1.7.2</serenity.maven.version>
<serenity.cucumber.version>1.6.5</serenity.cucumber.version>

**Example:**
Scenario Outline: Add account
    Given the account with following details: <accountType>,<heldBy>,<servicesSupported>
    When I update the acccount <field> to a <newValue>
    Then I should be informed of the successful account update    
    Examples: Add bank account
    |accountType|heldBy    |servicesSupported  |
    |bankaccount|individual|Deposit,Withdrawal |
    Examples: Add card account
    |accountType|heldBy    |servicesSupported  |
    |cardaccount|business  |Deposit,Withdrawal |

![image](https://user-images.githubusercontent.com/28475399/33160388-013c3acc-d070-11e7-9bd3-6f6d3a7e818e.png)

**Comment by cliviu** [comment]
hi @rraghuna . I cannot reproduce your issue. Can you please provide an example for us  ?  Thanks !

**Comment by rraghuna** [comment]
Hi @cliviu ,

Please find attached a sample project which reproduces this issue. Thanks.

**Comment by rraghuna** [comment]
Many thanks, @cliviu.

I have tested this issue and table title and the data are as per the input and not mixed up.
