### ISSUE TITLE
Serenity Report : Serenity fails to generate tests report when a scenario with two examples table is run by tags

### ISSUE THREAD

**Issue by Ram-Raghu** [serenity-bdd/serenity-cucumber#107]
**Desccription:**

Serenity fails to generate tests report when a scenario with two examples table is run by tags.

**Steps to Reproduce**:

1. Write a Gherkin scenario outline with Examples split into two like in the below example.
2. Ensure the second example table for the scenario contains more than one row (excluding the title row)
2. Run the test from maven (mvn clean verify -Dcucumber.options="--tags @add --tags @bank_account") and check the report.This would run the scenario that has **@add AND @bank_account** tags.

**Expected**:

The  example table row that is tagged with both @add and @bank_account should be run and Serenity should generate report containing the outcome of those tests.

**Actual**:

The example table row that is tagged with both @add and @bank_account is executed successfully but _Serenity fails to include the tests in the report._

**Note**: This happens only when the number of rows in the second example table for a scenario is greater than one (excluding the title row).

**Environment**:

<serenity.version>1.8.1</serenity.version>
<serenity.maven.version>1.8.0</serenity.maven.version>
<serenity.cucumber.version>1.6.5</serenity.cucumber.version>

**Scenario details:**

 @add
   Scenario Outline: Add account
    Given the account with following details: <accountType>,<heldBy>,<servicesSupported>
    When I update the acccount <field> to a <newValue>
    Then I should be informed of the successful account update   
      
    @bank_account
    Examples: Add bank account
    |accountType|heldBy    |servicesSupported  |
    |bankaccount|individual|Deposit,Withdrawal |
            
    @card_account
    Examples: Add card account
    |accountType|heldBy    |servicesSupported  |
    |cardaccount|business  |Deposit,Withdrawal |
    |cardaccount|business  |Deposit,Withdrawal |

**Project to replicate:**

[sample.zip](https://github.com/serenity-bdd/serenity-cucumber/files/1502797/sample.zip)

**Comment by rraghuna** [comment]
Hi John, 

Sorry to bother. I can see a pull request and a merge about 12 days ago for this ticket but do not see a newer version available in maven. Just wondering whats happening.

Thanks & Regards
Ram

**Comment by cliviu** [comment]
hi @rraghuna , try with 
`<dependency>
  <groupId>net.serenity-bdd</groupId>
  <artifactId>serenity-cucumber</artifactId>
  <version>1.6.7</version>
  <type>pom</type>
</dependency>`
, it should work now

**Comment by rraghuna** [comment]
Hi @cliviu 

Thank you very much for fixing this. I tested this in serneity cucumber version 1.6.7. 

Now Serenity report is generated with correct number of tests when the tests are triggered via maven command. 

However, when I populate the tags attribute as below in the @CucumberOptions annotation in the Junit Runner class, then I see the issue occuring.

```
@RunWith(CucumberWithSerenity.class)
@CucumberOptions(strict = false, **tags= {"@add or @bank_account"}**,features = "src/test/resources/features",glue= {"org.stepdefinitions"},
plugin = { "pretty", "json:target/cucumber-json-report.json","html:target/cucumber-html-report"})
public class AcceptanceTest {
	
}
```

**Comment by wakaleo** [comment]
Maybe take a look at the code yourself and propose a PR? If it works for command line options, it could be a simple fix

**Comment by rraghuna** [comment]
Hi @wakaleo , @cliviu 

The serenity report issue when tags in cucumber options contains logical Or, And and Not is fixed and the code is merged with the master branch. I need your kind assistance in publishing this code to the maven central repo.

**Comment by Ram-Raghu** [comment]
closed by #110  & #118

**Comment by vishalm** [comment]
Do not start by ~(Not opertaor in Gradle cucumber option)

For example : 
`-Dserenity.properties=test-properties/chrome.properties -Dcucumber.options="--tags ~@hybris" ` Observer this cucumber.option started with NOT operator so serenity failed to generate report 

`-Dserenity.properties=test-properties/chrome.properties -Dcucumber.options="--tags @positiveTag --tags ~@hybris" `  
Now your reports will work 

Bit wired but true :)

**Comment by pavitrajainqt** [comment]
Facing this issue, below is the serenity version i am using:
<serenity.version>1.9.14</serenity.version>
<serenity.maven.version>1.9.14</serenity.maven.version>
<serenity.cucumber.version>1.9.5</serenity.cucumber.version>

**Comment by wakaleo** [comment]
This is a closed issue - please read the thread and ensure you are using the new Cucumber tag syntax

**Comment by ebbesandslevin** [comment]
I got this error after first try:

![image](https://user-images.githubusercontent.com/47423361/115018112-c2d6e880-9eb7-11eb-91f0-8320bf8e676f.png)\
