### ISSUE TITLE
serenity.restart.browser.for.each=FEATURE is not working

### ISSUE THREAD

**Issue by BladeDark** [serenity-bdd/serenity-cucumber#116]
Serenity version: 1.7.0-rc.1
Serenity cucumber version: 1.6.2

I want to restart browser when executing change to next feature file
I try to use this "serenity.restart.browser.for.each=FEATURE" but it's not working

**Comment by wakaleo** [comment]
Try with the latest versions

**Comment by BladeDark** [comment]
@wakaleo 
try with Serenity version: 1.8.1
Cucumber version: 1.6.5

It's still not working

**Comment by wakaleo** [comment]
Latest versions are 1.8.11 and 1.6.7. Alternatively, try with lower case or capitalised “feature” (I don’t recall offhand).

**Comment by BladeDark** [comment]
try with Serenity version: 1.8.11
Cucumber version: 1.6.7

try with "feature" or "FEATURE" are still not working

**Comment by wakaleo** [comment]
It is most likely a project-specific issue then. If you can provide a sample project that reproduces the issue, I will take a look in the new year

**Comment by BladeDark** [comment]
I will provide it

**Comment by BladeDark** [comment]
Please check here
[Demo.zip](https://github.com/serenity-bdd/serenity-cucumber/files/1592562/Demo.zip)

**Comment by BladeDark** [comment]
@wakaleo 
Any updated ?

**Comment by wakaleo** [comment]
Update will be posted here when one of the Serenoty core team (or another member of the Serenity community) picks  this up. Unfortunately there is no SLA on open source issues unless you have a commercial support contract.

**Comment by wakaleo** [comment]
I can see this working correctly for 
serenity-core version: 1.8.21
serenity-cucumber version: 1.6.13

**Comment by BladeDark** [comment]
@wakaleo 
I try on
serenity-core version: 1.9.1
serenity.cucumber.version: 1.9.3

It's not working yet.

**Comment by wakaleo** [comment]
Indeed, I have reproduced the issue. Unfortunately this is not supported by the current Cucumber event model (I believe it was in Cucumber 1.x), so it won't be possible in Serenity either.

**Comment by BladeDark** [comment]
@wakaleo  
Thank you for your updating
