### ISSUE TITLE
Serenity Report: Serenity fails to generate test report with test outcomes when root folder of the features file is provided.

### ISSUE THREAD

**Issue by Ram-Raghu** [serenity-bdd/serenity-cucumber#120]
**Description**:

Serenity fails to generate test report with test outcomes when root folder of the features file is provided.

**Steps to Reproduce**:

1) Provide the root folder of features for the 'features' attribute in @CucumberOptions annotation in the Junit test (marked with @RunWith CucumberWithSerenity.class).
2) Run the test using maven or gradle.
3) The tests run are successfull. However, check the serenity report.

**Expected**:
Serenity report with tests outcome should be generated.

**Actual**:
Serenity report with tests outcome is not generated.

**Environment**:
<serenity.version>1.8.20</serenity.version>
<serenity.maven.version>1.8.5</serenity.maven.version>
<serenity.cucumber.version>1.6.9</serenity.cucumber.version>

**Comment by wakaleo** [comment]
A few quick comments:
  - Always make sure the serenity version and the serenity maven version are the same
  - The root folder is a file path, so it needs to be 'src/test/features'
  - This should work just fine, but if it doesn't the problem is most likely elsewhere - the @CucumberWithSerenity options have no relationship with the report generation.

**Comment by Ram-Raghu** [comment]
Hi @wakaleo 

1) point taken
2) yes, I meant the same. The root folder in my case is src/test/resources as well.
3) Apologies for not being clear. When the tests are run by tags when only root folder of features is provided, this issue occurs.

Hope this is clear. Please let me know otherwise. I debugged the code and have proposed PR #121 .  Please let me know if I you have any comments or questions. Thank you.

**Comment by wakaleo** [comment]
Thanks, yes, the combination of tags and root was the triggering factor. Thanks for your fix!

**Comment by Ram-Raghu** [comment]
Thank you for your prompt response, review and merge.
