### ISSUE TITLE
NullPointerException Running Cucumber with Serenity feature files directly from IntelliJ

### ISSUE THREAD

**Issue by nomadcanuck** [serenity-bdd/serenity-cucumber#130]
Attempting to run cucumber feature file with serenity directly from IntelliJ produces NullPointerException when using serenity-cucumber v1.6.13. 

Workaround is to use serenity-cucumber v1.6.10 with serenity v1.8.21.

Steps to reproduce:
1. serenity.version=1.9.0-rc.3 or 1.8.21
1. serenity.cucumber.version=1.6.13
1. setup and run as described in John Ferguson Smart blog at [Running Cucumber with Serenity feature files directly from IntelliJ](https://johnfergusonsmart.com/running-cucumber-serenity-feature-files-directly-intellij/)

`
Exception in thread "main" java.lang.NullPointerException
	at cucumber.runtime.formatter.SerenityReporter.initLineFilters(SerenityReporter.java:365)
	at cucumber.runtime.formatter.SerenityReporter.<init>(SerenityReporter.java:100)
	at net.serenitybdd.cucumber.CucumberWithSerenityRuntime.createSerenityEnabledRuntime(CucumberWithSerenityRuntime.java:37)
	at net.serenitybdd.cucumber.CucumberWithSerenityRuntime.using(CucumberWithSerenityRuntime.java:23)
	at net.serenitybdd.cucumber.cli.Main.run(Main.java:27)
	at net.serenitybdd.cucumber.cli.Main.main(Main.java:18)
`

**Comment by wakaleo** [comment]
What version of IntelliJ are you using?

**Comment by nomadcanuck** [comment]
Sorry about that, the IntelliJ version in use is:
IntelliJ IDEA 2017.3.5 EAP (Ultimate Edition)
Build #IU-173.4674.1, built on February 26, 2018

**Comment by asvdw** [comment]
SerenityReporter constructor needs CucumberWithSerenity.currentRuntimeOptions() but CucumberWithSerenity.setRuntimeOptions(RuntimeOptions runtimeOptions) is called _after_ ==> NPE :(

**Comment by wakaleo** [comment]
Thanks for finding this - the IntelliJ API may have changed. Please feel free to provide a PR as I won’t have time to look into this any time soon

**Comment by asvdw** [comment]
using cucumber.api.cli.Main as Main class seems to do the trick. Try to edit run configuration (in intelliJ, Run/Edit Configurations...) and use `cucumber.api.cli.Main` instead of `net.serenitybdd.cucumber.cli.Main`

**Comment by wakaleo** [comment]
@asvdw If you use cucumber.api.cli.Main you won't be running the feature file as a Serenity test.

**Comment by asvdw** [comment]
Yes I know, but it was ok for debugging purpose.
Here is the simple fix ;)

**Comment by henry6000** [comment]
Can some please create a version with this fix as it affected anyone using the cli

**Comment by hweerasooriya** [comment]
Can anyone fix the above-mentioned issue?

**Comment by wakaleo** [comment]
Should be fixed in serenity-cucumber 1.9.4

**Comment by hweerasooriya** [comment]
Thank you. Updating a new serenity cucumber version.
