### ISSUE TITLE
serenity reports

### ISSUE THREAD

**Issue by vi123ch** [serenity-bdd/serenity-cucumber#133]
Hello,

I have multiple test scenarios and feature files. I want to know if the logs information can be displayed in the Serenity reports. Currently now I am creating them in a different place but using serenity reports is there a possibility to display reports with logs (nothing but in the tests I check if some pages have some text, if text missing I store the currenturl into a log file). Your help would be appreciated. Thanks in advance.

**Comment by mehtadishakalpeshbhai** [comment]
I am not sure if I got your question. But what I understood is that you want reports which can give you logs. After running your tests, you can go to /build/reports/tests/test/index.html. This path will show you one report and clicking on tests link you can see the logs. Let me know if it works

**Comment by wakaleo** [comment]
To add log files to the reports, you can do something like this:
```
Serenity.recordReportData().withTitle("Some data").fromFile(testDataSource)
```
