### ISSUE TITLE
Serenity + Cucumber + IE 11 

### ISSUE THREAD

**Issue by vi123ch** [serenity-bdd/serenity-cucumber#136]
Hello,

I am trying to do my tests using Selenium grid and one of the test is lengthy to perform. But for some reason, the browser gets closed in between. Being a lengthy test case its difficult to debug and check where and why there is a failure. Could you please help me!!! Thanks in advance

**Comment by wakaleo** [comment]
This is most likely IE or the webdriver binary crashing - generally unrelated to the Selenium or Serenity code. If you have any log messages you can share them with the IE Webdriver community who might be able to help.

**Comment by vi123ch** [comment]
Hello,
My error is this, functionorg.openqa.selenium.JavascriptException: JavaScript error. I am using a function for pageload which is this, 
  public void waitForPageLoad(WebDriver driver)
    {
        try {
            Wait<WebDriver> wait = new WebDriverWait(driver, 40);
            wait.until(new Function<WebDriver, Boolean>()
            {
                @Override
                public Boolean apply(WebDriver driver)
                {
                     return String.valueOf(((JavascriptExecutor) driver).executeScript("return document.readyState"))
                        .equals("complete");
                }
            });
        } catch (Exception e) {
            logger.warn(e);
        }
    }

Any help !!!

**Comment by wakaleo** [comment]
As far as I can see this is not a Serenity defect (Selenium is just reporting a JS error from the browser) so it would be better to post it on https://serenity-bdd.rocket.chat
