### ISSUE TITLE
language spanish for features and definitions with serenity 

### ISSUE THREAD

**Issue by mpuertao** [serenity-bdd/serenity-cucumber#140]
Good day, regards

Cucumber is compatible with language Spanish for FEATURE and with serenity for documentation living?. 
Is the language configurable in the serenity.properties?

Thank you very much for the help

**Comment by wakaleo** [comment]
Yes, Serenity doesn't care what language your feature files are in. You can ask for more details on the community forum at https://serenity-bdd.rocket.chat.
