### ISSUE TITLE
Narrative of first executed feature is used for all features with the same Feature name in a report

### ISSUE THREAD

**Issue by bristly** [serenity-bdd/serenity-cucumber#142]
If two feature files has the same feature name (Feature: Test 1) and different narrative the Serenity report will have the narrative of the first executed feature only for both of features.

<serenity.version>1.9.7</serenity.version>
<serenity.maven.version>1.9.7</serenity.maven.version>
<serenity.cucumber.version>1.9.4</serenity.cucumber.version>

**Comment by wakaleo** [comment]
This capability won't be supported at this stage - it is preferable to avoid having multiple features with the same name.
