### ISSUE TITLE
trying to set CUCUMBER_OPTIONS in environment but not working for multiple tags

### ISSUE THREAD

**Issue by markl2** [serenity-bdd/serenity-cucumber#150]
I can do `export CUCUMBER_OPTIONS="--tags @reliable"` successfully
but: `export CUCUMBER_OPTIONS="--tags {@reliable, @unreliable}"` gives errors as well as: `export CUCUMBER_OPTIONS="--tags @reliable, @unreliable"`
The error given for the former export is: `java.lang.IllegalArgumentException: Not a file or directory: /var/lib/jenkins/workspace/Dashboard-Test-Automation-QA-reliable/unreliable}`

BTW, I am logged into my Jenkins server (RHEL 7.4) and running everything from the command line in directory `/var/lib/jenkins/workspace/Dashboard-Test-Automation-QA-reliable` to troubleshoot this and not using Jenkins.

Any suggestions?  If this is the wrong place to post this, please advise.
thx,
Mark

I am using older versions of "stuff" but I think this might be a general issue.
The relevant stuff from my POM is:
>
     <properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<java.version>1.8</java.version>
		<maven.compiler.source>1.8</maven.compiler.source>
		<maven.compiler.target>1.8</maven.compiler.target>
		<junit.version>4.12</junit.version>
		<maven-failsafe-plugin.version>2.20.1</maven-failsafe-plugin.version>
		<slf4j-simple.version>1.6.1</slf4j-simple.version>
		<serenity-core.version>1.6.3</serenity-core.version>
		<serenity-cucumber.version>1.5.9</serenity-cucumber.version>
		<serenity.version>1.6.3</serenity.version>
		<serenity.maven.version>1.6.3</serenity.maven.version>
		<selenium-firefox-driver.version>3.6.0</selenium-firefox-driver.version>
		<selenium-ie-driver.version>3.6.0</selenium-ie-driver.version>
		<selenium-chrome-driver.version>3.4.0</selenium-chrome-driver.version>
		<webdriver.driver>firefox</webdriver.driver>
		<rest.assured.version>3.0.6</rest.assured.version>
	</properties>

**Comment by wakaleo** [comment]
@cliviu?

**Comment by cliviu** [comment]
hi @markl2 , pleaser try --tags '@reliable or @unreliable' . Here is the docu of the tag expressions, the new style  : https://github.com/cucumber/cucumber/tree/master/tag-expressions

**Comment by cliviu** [comment]
@markl2 ?

**Comment by wakaleo** [comment]
Closing as the solution has been provided by @cliviu
