### ISSUE TITLE
Stories tag appearing on Over All Test Summary section of Srenity - Cucumber report

### ISSUE THREAD

**Issue by saurabhmgm** [serenity-bdd/serenity-cucumber#16]
Hi John,
Is there any specific reasoning for having stories tag for cucumber - serenity report. 
I used Serenity - 1.0.47
Serenity-Cucumber - 1.0.15

I can see Features and stories as repetitive. Expected to see only Features.

**Comment by wakaleo** [comment]
Hi, I think this has been fixed in 1.0.18, could you verify?

**Comment by YamStranger** [comment]
it seems that this issue was fixed and now can't be reproduced.
