### ISSUE TITLE
Add Tags to Example

### ISSUE THREAD

**Issue by poorvikamahesh** [serenity-bdd/serenity-cucumber#169]
Hello,

I am trying to run a suite of scenarios with different sets of user data. The user data I am providing via examples have different roles. Therefor I want the same set if test cases to run for different user logins by providing tags to each of the Example entry. For example

Scenario: Login Module

Given I am on the application
When I login with username: "/<userid/>" and password: "/<password/>"
Then the home page is displayed

@admin
Examples:
| userid | password |
| admin | XXXXXXX|

@customer
Examples:
| userid | password |
| cust1  | XXXXXXX|

I am not able to achieve this via the above syntax. Kindly help

Thank you!

**Comment by wakaleo** [comment]
This is a Cucumber-JVM question, not a Serenity one, but I believe the above syntax should work. What behaviour are you seeing?

**Comment by wakaleo** [comment]
@WithTag is for JUnit tests, try using the CucumberOptiona tag attribute instead

**Comment by poorvikamahesh** [comment]
@wakaleo
That worked... thanks a lot
