### ISSUE TITLE
Serenity report showing Page not found for Releases tab

### ISSUE THREAD

**Issue by rohitpatwari84** [serenity-bdd/serenity-cucumber#172]
I see Releases Tab in Report . But it seems no html related to it is present .

Details - 
        <serenity.version>1.9.26</serenity.version>
        <serenity.maven.version>1.9.26</serenity.maven.version>
        <serenity.cucumber.version>1.9.8</serenity.cucumber.version>

@version:Release2
@version:Sprint2
Feature: Login Functionality
@Smoke
  Scenario: User is able to login successfully using valid credentials
    Given User is on the login Page
    When User submits valid credentials
    Then USer is logged in successfully

**Comment by wakaleo** [comment]
Release reporting is no longer supported - where are you seeing the tab?

**Comment by rohitpatwari84** [comment]
I am seeing on the Report  after I run serenity aggregate(index.html in target/site/serenity/index,html)

**Comment by rohitpatwari84** [comment]
And is there any any other way to specify Release in our Report ?

**Comment by wakaleo** [comment]
Just use normal tags.

**Comment by rohitpatwari84** [comment]
Sorry didnt get you..Like @version doesnt work as you mentioned.Then how to specify Release through Tags ?

**Comment by wakaleo** [comment]
We have dropped explicit support of releases as a separate page for now, but you can still use the normal tag pages to view results per version.

**Comment by wakaleo** [comment]
The expand button shows the full description of the epic - if you don't have any text in the description, nothing will appear.

**Comment by rohitpatwari84** [comment]
Oh ok..I thought it will show features as a children nodes.
