### ISSUE TITLE
Modelling Requirements in Cucumber Feature 

### ISSUE THREAD

**Issue by shreyasarjun** [serenity-bdd/serenity-cucumber#190]
I am working on Serenity BDD+Cucumber+Junit+RestAssured.
Serenity reporting is picked based on @Test annotations and put in stories tab in reporting 
But I have used cucumber feature file Hence there is no @Test annotations in my framework.
My framework contains runner file,feature file and step definitions So I have only following annotations
@Given,@When  and @Then. 
I need serenity reporting structure like Overall Test Results,Requirements Tab,Features Tab and Stories Tab.
So How Can I configure serenity reports for getting above format.
As of now I am getting reporting as `follows`
I am using serenity-core: 1.4.1-rc.6 and serenity-cucumber: 1.1.6

![report1](https://user-images.githubusercontent.com/13919078/49694140-0fa0ab00-fbaa-11e8-9233-5f3fc24bc692.jpg)
![report1contiune](https://user-images.githubusercontent.com/13919078/49694141-10394180-fbaa-11e8-847b-952a99257785.jpg)

Feature: Perform APITesting for static microservice on item

@SMOKE 
Scenario: Retrieve the list of avialable promotions for given itemID
When Send the request json with ItemID
Then Verify the available promotions in the response json

@REGRESSION
Scenario: Retrieve the list of avialable promotions for given mutiples itemIDs
When Send the request json with multiple itemids
Then Verify the list of available promotions in the response json

**Comment by wakaleo** [comment]
See https://serenity-bdd.github.io/theserenitybook/latest/ - also, your versions are very old, you will need to update them for best results. Since this is a usage question and not a defect, please continue the conversation on https://serenity-bdd.rocket.chat.

**Comment by shreyasarjun** [comment]
I have tried to use latest version as serenity-core:2.0.20 and serenity-cucumber:1.9.21 But getting following error like

maven-metadata-serenity.xml: only whitespace content allowed before start tag and not T (position: START_DOCUMENT seen      \r\n   T... @2:5) 
[WARNING] Rule 0: org.apache.maven.plugins.enforcer.RequireUpperBoundDeps failed with message:
Failed while enforcing RequireUpperBoundDeps. The error(s) are [
Require upper bound dependencies error for net.bytebuddy:byte-buddy:1.8.12 paths to dependency are:
+-com.promotion.apitesting:promotiontesting:0.0.1-SNAPSHOT
  +-net.serenity-bdd:serenity-core:2.0.20
    +-net.bytebuddy:byte-buddy:1.8.12

Could you please provide some guidelines to resolve this error.

**Comment by wakaleo** [comment]
Could be a dependency conflict or a corrupt Maven repo. Try deleting your .m2/repository directory and running a dependency analysis.

**Comment by shreyasarjun** [comment]
I have modified some rules in maven-enforcer-plugin configuration , Now its working fine.
Thanks @wakaleo
