### ISSUE TITLE
Error running features from command line with tags expression

### ISSUE THREAD

**Issue by ricardorlg** [serenity-bdd/serenity-cucumber#193]
I get initialization error when trying to run tests from command line using new tag expression from cucumber, for example 

CUCUMBER_OPTIONS='--tags "@smoke and @fast"' mvn verify will give the error.

**Comment by wakaleo** [comment]
This seems to happen when the quotes are used in that order; try CUCUMBER_OPTIONS="--tags '@smoke and @fast'"

**Comment by ricardorlg** [comment]
yes, I just get it to work,  I will close this.
