### ISSUE TITLE
<Question> Is there a way to get all the Tags of scenario during run time in stepdefinition??

### ISSUE THREAD

**Issue by srinivasbudh** [serenity-bdd/serenity-cucumber#199]
I have a scenario where I want to manage some test data based on the scenariotags, but during runtime I'm unable to scenario tags, Is it possible to fetch tags while running @Step methods?? if yes, can anyone help with it??

Thanks in advance

**Comment by wakaleo** [comment]
You might be able to access the tags via the StepEventBus, though I don’t have the code in front of me.

**Comment by wakaleo** [comment]
Try
```
StepEventBus.getEventBus().getBaseStepListener().latestTestOutcome().get().getTags()
```

**Comment by srinivasbudh** [comment]
Thanks for the quick response, will check and confirm shortly

**Comment by srinivasbudh** [comment]
Thanks a Lot @wakaleo Solution you provided works great 

`StepEventBus.getEventBus().getBaseStepListener().latestTestOutcome().get().getTags()`

returns set of TestTag's. upon iterating through the set and using getName() methods I'm able to get the exact Tag that I'm looking for.

Thanks a lot for you help
