### ISSUE TITLE
Serenity-cucumber implementation for ruby and protractor

### ISSUE THREAD

**Issue by eymemathew** [serenity-bdd/serenity-cucumber#20]
Hi does anyone know of any similar implementation for ruby and protractor. I'm looking at using serenity with cucumber. Found a ruby gem for serenity but that isn't the same as this module. Any information regarding this would be great.

**Comment by wakaleo** [comment]
Serenity uses JVM byte instrumentation, so at this stage it is exclusively for Cucumber-Java or other JVM implementations.
