### ISSUE TITLE
How to run tag wise Scenario Outline ?? 

### ISSUE THREAD

**Issue by sifulovi** [serenity-bdd/serenity-cucumber#204]
My code is 

@WithTags({@WithTag("Login")})
@CucumberOptions(
        format = { "pretty" [},](url)
        glue = {"starter.stepdefinitions"},
        features = {"src/test/resources/features"}

)
I have two tags @login, @CBC, I want to run @Login before @CBC
but it all time run with firstly @CBC then @Login.(@WithTags is not working :( )

![image](https://user-images.githubusercontent.com/11840131/56858029-e97f7a00-6995-11e9-9df0-891e9710c1f3.png)

here is my features files structure,

**Comment by wakaleo** [comment]
@WithTags is for JUnit, not Cucumber - see the Cucumber docs to see how to define tags in the @CucumberOptions parameters. But you cannot control the order of execution of feature files using tags - feature files (and scenarios) are meant to be independent, so your Create-Blog-Category.feature should not depend on the login.feature to work (feature files are not test scripts). Each scenario needs to be independent. See https://johnfergusonsmart.com/1136-2/.
