### ISSUE TITLE
Why buildscript needed ?

### ISSUE THREAD

**Issue by sifulovi** [serenity-bdd/serenity-cucumber#206]
If i write the below code 

```
buildscript {
    repositories {
        mavenLocal()
        jcenter()
    }
    dependencies {
        classpath("net.serenity-bdd:serenity-gradle-plugin:2.0.48")
    }
}
```
Then reports generate with index.html .

**Comment by wakaleo** [comment]
https://serenity-bdd.rocket.chat is a better place for general questions like this. This code lets Gradle find the Serenity plugin. It's the `test.finalizedBy(aggregate)` code that actually generates the reports.

**Comment by sifulovi** [comment]
Ok, 
Sir, I am writing on rocket chat.
