### ISSUE TITLE
Unable to run serenity cucumber from command line

### ISSUE THREAD

**Issue by basheermohd** [serenity-bdd/serenity-cucumber#211]
Unable to run serenity cucumber from command line using "mvn verify" command.
I am able to run from pom.xml using eclipse and test runner class, but the issue is only with when i run from command prompt, below error i am getting.

[INFO] Running starter.TestRunner
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.013 s <<< FAILURE! - in starter.TestRunner
[ERROR] initializationError(starter.TestRunner)  Time elapsed: 0.013 s  <<< ERROR!
**java.lang.NoClassDefFoundError: cucumber/runner/TimeServiceEventBus
Caused by: java.lang.ClassNotFoundException: cucumber.runner.TimeServiceEventBus**

[INFO] Running starter.TestRunner
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.009 s <<< FAILURE! - in starter.TestRunner
[ERROR] initializationError(starter.TestRunner)  Time elapsed: 0.009 s  <<< ERROR!
java.lang.NoClassDefFoundError: cucumber/runner/TimeServiceEventBus
Caused by: java.lang.ClassNotFoundException: cucumber.runner.TimeServiceEventBus

[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR] starter.TestRunner.initializationError(starter.TestRunner)
[ERROR]   Run 1: TestRunner.initializationError » NoClassDefFound cucumber/runner/TimeServiceEv...
[ERROR]   Run 2: TestRunner.initializationError » NoClassDefFound cucumber/runner/TimeServiceEv...
[INFO]
[INFO]
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0

**Comment by basheermohd** [comment]
let me know if my pom.xml is needed

**Comment by wakaleo** [comment]
That would be a dependency issue of some kind - try posting on https://serenity-bdd.rocket.chat to get help from the Serenity community.

**Comment by wakaleo** [comment]
Closed for lack of activity.
