### ISSUE TITLE
Tests getting skipped/not getting executed with multiple tags

### ISSUE THREAD

**Issue by push2212** [serenity-bdd/serenity-cucumber#239]
Hello  ,

I am trying to run 2 scenarios in same feature file as a maven goal.

clean verify -Dcucumber.options="--tags '@TC001 and @TC002'"

Single tag runs successfully , however more than one creates an issue. I went through all Serenity Cucumber issues and tried all possible ways ,  however could not resolve the issue.

Please help.

------------------------------------------------------------
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------< net.serenitybdd.starter:SerenityBDDCucumber >-------------
[INFO] Building Serenity BDD using Cucumber 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ SerenityBDDCucumber ---
[INFO] Deleting C:\Work\SerenityBDDCucumber\target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ SerenityBDDCucumber ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Work\SerenityBDDCucumber\src\main\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ SerenityBDDCucumber ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ SerenityBDDCucumber ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 12 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ SerenityBDDCucumber ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 9 source files to C:\Work\SerenityBDDCucumber\target\test-classes
[INFO] /C:/Work/SerenityBDDCucumber/src/test/java/utilities/common.java: Some input files use or override a deprecated API.
[INFO] /C:/Work/SerenityBDDCucumber/src/test/java/utilities/common.java: Recompile with -Xlint:deprecation for details.
[INFO] 
[INFO] --- maven-surefire-plugin:3.0.0-M4:test (default-test) @ SerenityBDDCucumber ---
[INFO] Tests are skipped.
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ SerenityBDDCucumber ---
[WARNING] JAR will be empty - no content was marked for inclusion!
[INFO] Building jar: C:\Work\SerenityBDDCucumber\target\SerenityBDDCucumber-1.0.0-SNAPSHOT.jar
[INFO] 
[INFO] --- maven-failsafe-plugin:3.0.0-M4:integration-test (default) @ SerenityBDDCucumber ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
Jun 11, 2020 8:44:24 PM io.cucumber.core.options.CucumberPropertiesParser parse
WARNING: Passing commandline options via the property `cucumber.options` has been deprecatedin favour of explicitly using property names.
Please use these instead: [cucumber.ansi-colors.disabled, cucumber.execution.dry-run, cucumber.execution.limit, cucumber.execution.order, cucumber.execution.strict, cucumber.execution.wip, cucumber.features, cucumber.filter.name, cucumber.filter.tags, cucumber.glue, cucumber.object-factory, cucumber.plugin, cucumber.snippet-type]

20:44:24.620 [main] WARN  i.c.junit.CucumberSerenityRunner - By default Cucumber is running in --non-strict mode.
This default will change to --strict and --non-strict will be removed.
You can use --strict or @CucumberOptions(strict = true) to suppress this warning

Feature from file:///C:/Work/SerenityBDDCucumber/src/test/resources/features/Login.feature
20:44:25.593 [pool-1-thread-1] INFO   - 

-------------------------------------------------------------------------------------
     _______. _______ .______       _______ .__   __.  __  .___________.____    ____ 
    /       ||   ____||   _  \     |   ____||  \ |  | |  | |           |\   \  /   / 
   |   (----`|  |__   |  |_)  |    |  |__   |   \|  | |  | `---|  |----` \   \/   /  
    \   \    |   __|  |      /     |   __|  |  . `  | |  |     |  |       \_    _/   
.----)   |   |  |____ |  |\  \----.|  |____ |  |\   | |  |     |  |         |  |     
|_______/    |_______|| _| `._____||_______||__| \__| |__|     |__|         |__|    
                                                                                     
 News and tutorials at http://www.serenity-bdd.info                                  
 Documentation at https://wakaleo.gitbooks.io/the-serenity-book/content/             
 Join the Serenity Community on Gitter: https://gitter.im/serenity-bdd/serenity-core 
 Serenity BDD Support and Training at http://serenity-bdd.info/#/trainingandsupport  
-------------------------------------------------------------------------------------

20:44:25.598 [pool-1-thread-1] INFO   - Test Suite Started: Test Cura Healthcare

0 Scenarios
0 Steps
0m
0.255s

[INFO] Running starter.CucumberTestSuite
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in starter.CucumberTestSuite
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- serenity-maven-plugin:2.2.7:aggregate (serenity-reports) @ SerenityBDDCucumber ---
[INFO] Test results for 0 tests generated in 875 ms in directory: file:/C:/Work/SerenityBDDCucumber/target/site/serenity/
[INFO] -----------------------------------------
[INFO]  SERENITY TESTS : SUCCESS
[INFO] -----------------------------------------
[INFO] | Tests executed         | 0
[INFO] | Tests passed           | 0
[INFO] | Tests failed           | 0
[INFO] | Tests with errors      | 0
[INFO] | Tests compromised      | 0
[INFO] | Tests pending          | 0
[INFO] | Tests ignored/skipped  | 0
[INFO] ------------------------ | --------------
[INFO] | Total Duration         | 000ms
[INFO] | Fastest test took      | 000ms
[INFO] | Slowest test took      | 000ms
[INFO] -----------------------------------------
[INFO] 
[INFO] SERENITY REPORTS
[INFO]   - Full Report: file:///C:/Work/SerenityBDDCucumber/target/site/serenity/index.html
[INFO] 
[INFO] --- maven-failsafe-plugin:3.0.0-M4:verify (default) @ SerenityBDDCucumber ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12.530 s
[INFO] Finished at: 2020-06-11T20:44:28+05:30
[INFO] ------------------------------------------------------------------------

**Comment by wakaleo** [comment]
Try `clean verify -Dcucumber.options="--tags '@tc001 or @tc002'`

**Comment by push2212** [comment]
It worked 💯 , thanks a lot , I have been looking for solution for so long. Closing the issue now.
