### ISSUE TITLE
Unable to execute project Tests with latest serenity , cucumber version

### ISSUE THREAD

**Issue by arm235** [serenity-bdd/serenity-cucumber#241]
My project is using below versions for serenity and cucumber:

                 <serenity.version>2.0.91</serenity.version>
		<serenity.maven.version>2.0.91</serenity.maven.version>
		<serenity.cucumber.version>1.0.30</serenity.cucumber.version>
		<cucumber.version>4.8.0</cucumber.version>
		<logback.version>1.2.3</logback.version>

If I set it to latest version as mentioned below unable to execute tests using mvn verify/mvn clean install.

                <serenity.version>2.2.8</serenity.version>
		<serenity.maven.version>2.2.8</serenity.maven.version>
		<serenity.cucumber.version>1.9.51</serenity.cucumber.version>
		<cucumber.version>4.8.0</cucumber.version>

`C:\Users\741467\eclipse-workspace\Lyvecloud-UI-Automation>mvn clean install | tee log_7_6_3.txt
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for net.serenitybdd.starter:Lyvecloud-UI-Automation:jar:1.0.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-jar-plugin is missing. @ line 185, column 12
[WARNING] 'build.plugins.plugin.version' for org.codehaus.mojo:build-helper-maven-plugin is missing. @ line 237, column 12
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO]
[INFO] ----------< net.serenitybdd.starter:Lyvecloud-UI-Automation >-----------
[INFO] Building Serenity BDD project using Cucumber 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from central: https://jcenter.bintray.com/net/serenity-bdd/maven/plugins/serenity-maven-plugin/2.2.8/serenity-maven-plugin-2.2.8.pom
Downloaded from central: https://jcenter.bintray.com/net/serenity-bdd/maven/plugins/serenity-maven-plugin/2.2.8/serenity-maven-plugin-2.2.8.pom (8.5 kB at 1.4 kB/s)
[WARNING] The POM for org.apache.commons:commons-exec:jar:1.1 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for org.eclipse.jetty.websocket:websocket-client:jar:9.4.20.v20190813 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ Lyvecloud-UI-Automation ---
[INFO] Deleting C:\Users\741467\eclipse-workspace\Lyvecloud-UI-Automation\target
[INFO]
[INFO] --- build-helper-maven-plugin:3.2.0:timestamp-property (current-time) @ Lyvecloud-UI-Automation ---
[WARNING] Using platform locale (en_US actually) to format date/time, i.e. build is platform dependent!
[INFO]
[INFO] --- maven-resources-plugin:2.4:copy-resources (copy-web.xml) @ Lyvecloud-UI-Automation ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-resources-plugin:2.4:resources (default-resources) @ Lyvecloud-UI-Automation ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\741467\eclipse-workspace\Lyvecloud-UI-Automation\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ Lyvecloud-UI-Automation ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 16 source files to C:\Users\741467\eclipse-workspace\Lyvecloud-UI-Automation\target\classes
[ERROR] error reading C:\Users\741467\.m2\repository\joda-time\joda-time\2.7\joda-time-2.7.jar; invalid LOC header (bad signature)
[INFO]
[INFO] --- maven-resources-plugin:2.4:testResources (default-testResources) @ Lyvecloud-UI-Automation ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 14 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.7.0:testCompile (default-testCompile) @ Lyvecloud-UI-Automation ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 3 source files to C:\Users\741467\eclipse-workspace\Lyvecloud-UI-Automation\target\test-classes
[ERROR] error reading C:\Users\741467\.m2\repository\joda-time\joda-time\2.7\joda-time-2.7.jar; invalid LOC header (bad signature)
[INFO]
[INFO] --- maven-surefire-plugin:2.22.1:test (default-test) @ Lyvecloud-UI-Automation ---
[INFO] Tests are skipped.
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ Lyvecloud-UI-Automation ---
[INFO] Building jar: C:\Users\741467\eclipse-workspace\Lyvecloud-UI-Automation\target\Lyvecloud-UI-Automation-1.0.0-SNAPSHOT.jar
[INFO]
[INFO] --- maven-failsafe-plugin:2.22.1:integration-test (default) @ Lyvecloud-UI-Automation ---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Users/741467/.m2/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/741467/.m2/repository/org/slf4j/slf4j-log4j12/1.7.7/slf4j-log4j12-1.7.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO]
[INFO] --- serenity-maven-plugin:2.2.8:aggregate (serenity-reports) @ Lyvecloud-UI-Automation ---
[INFO] Test results for 0 tests generated in 4 secs in directory: file:/C:/Users/741467/eclipse-workspace/Lyvecloud-UI-Automation/target/site/serenity_06-07-2020_13-29-20/
[INFO] -----------------------------------------
[INFO]  SERENITY TESTS : SUCCESS
[INFO] -----------------------------------------
**[INFO] | Tests executed         | 0
[INFO] | Tests passed           | 0
[INFO] | Tests failed           | 0
[INFO] | Tests with errors      | 0
[INFO] | Tests compromised      | 0
[INFO] | Tests pending          | 0
[INFO] | Tests ignored/skipped  | 0
[INFO] ------------------------ | --------------
[INFO] | Total Duration         | 000ms
[INFO] | Fastest test took      | 000ms
[INFO] | Slowest test took      | 000ms**
[INFO] -----------------------------------------
[INFO]
[INFO] SERENITY REPORTS
[INFO]   - Full Report: file:///C:/Users/741467/eclipse-workspace/Lyvecloud-UI-Automation/target/site/serenity_06-07-2020_13-29-20/index.html
[INFO]
[INFO] --- maven-failsafe-plugin:2.22.1:verify (default) @ Lyvecloud-UI-Automation ---
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ Lyvecloud-UI-Automation ---
[INFO] Installing C:\Users\741467\eclipse-workspace\Lyvecloud-UI-Automation\target\Lyvecloud-UI-Automation-1.0.0-SNAPSHOT.jar to C:\Users\741467\.m2\repository\net\serenitybdd\starter\Lyvecloud-UI-Automation\1.0.0-SNAPSHOT\Lyvecloud-UI-Automation-1.0.0-SNAPSHOT.jar
[INFO] Installing C:\Users\741467\eclipse-workspace\Lyvecloud-UI-Automation\pom.xml to C:\Users\741467\.m2\repository\net\serenitybdd\starter\Lyvecloud-UI-Automation\1.0.0-SNAPSHOT\Lyvecloud-UI-Automation-1.0.0-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  44.607 s
[INFO] Finished at: 2020-07-06T13:29:47+05:30
[INFO] ------------------------------------------------------------------------`

**Comment by wakaleo** [comment]
Version 2.2.8 needs serenity-cucumber5 (see https://github.com/serenity-bdd/serenity-cucumber-starter)

**Comment by arm235** [comment]
It worked! Thank you so much. Closing the issue.
