### ISSUE TITLE
Overall results pass even the one of the step failed

### ISSUE THREAD

**Issue by ChakravarthiS** [serenity-bdd/serenity-cucumber#252]
Hi ,

I am using Cucumber with Serenity. In one of the scenario, i have a failed step but overall scenario result is passed in Serenity reports. Please find the versions I am using.

        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <serenity.version>2.3.6</serenity.version>
        <serenity.maven.version>2.3.6</serenity.maven.version>
        <serenity.cucumber.version>2.3.6</serenity.cucumber.version>
        <encoding>UTF-8</encoding>

Thanks,
Chakri

**Comment by wakaleo** [comment]
Can you provide a project that reproduces this behaviour?

**Comment by ChakravarthiS** [comment]
Hi Wakaleo,

The issue i have faced is because of target folder refresh. Sorry for the trouble. I am closing the ticket. 
Thank you for the quick response.

Thanks,
Chakri
