### ISSUE TITLE
Serenity reports unreadable when run in parallel

### ISSUE THREAD

**Issue by szanelato** [serenity-bdd/serenity-cucumber#255]
Hi there,

@wakaleo I follow these [tutorial](https://johnfergusonsmart.com/running-parallel-tests-serenity-bdd-cucumber/) to execute my serenity project using the parallel strategy, it runs correctly although some of my tests went failed when I use this strategy. So I came to check my serenity reports to give me insights of which scenarios are failing but it is unreadable and looks like it is showing only a half of tests execution even using `<parallelScheme>FEATURE</parallelScheme>` instead of SCENARIO as advised.

My serenity report:
![image](https://user-images.githubusercontent.com/59705574/106787241-3d6cc780-662e-11eb-9ac5-c16b00eaca69.png)

Where unfilled coverage bars are gaps in execution, preventing me from getting the evidence for those scenarios. Whereas when I click in features tab and select a failed scenario the files is always missing.

My pom.xml:

    <plugins>
      <plugin>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>2.20</version>
        <configuration>
          <parallel>classes</parallel>
          <threadCount>2</threadCount>
        </configuration>
      </plugin>
      <plugin>
        <artifactId>maven-failsafe-plugin</artifactId>
        <version>2.20</version>
        <configuration>
          <systemPropertyVariables>
            <webdriver.base.url>${webdriver.base.url}</webdriver.base.url>
          </systemPropertyVariables>
          <parallel>classes</parallel>
          <threadCountClasses>2</threadCountClasses>
          <useUnlimitedThreads>true</useUnlimitedThreads>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>integration-test</goal>
              <goal>verify</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.2</version>
        <configuration>
          <source>1.8</source>
          <target>1.8</target>
        </configuration>
      </plugin>
      <plugin>
        <groupId>com.github.temyers</groupId>
        <artifactId>cucumber-jvm-parallel-plugin</artifactId>
        <version>4.2.0</version>
        <executions>
          <execution>
            <id>generateRunners</id>
            <phase>generate-test-sources</phase>
            <goals>
              <goal>generateRunners</goal>
            </goals>
            <configuration>
              
              
              <glue>
                <package>src/test/resources/features</package>
              </glue>
              <parallelScheme>FEATURE</parallelScheme>
              <customVmTemplate>src/test/resources/cucumber-serenity-runner.vm</customVmTemplate>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>

**Comment by wakaleo** [comment]
This plugin is no longer supported - use the latest version of serenity with serenity-cucumber6
