### ISSUE TITLE
Not Getting the serenity BDD report properly with total counts

### ISSUE THREAD

**Issue by anweshadhal** [serenity-bdd/serenity-cucumber#261]
I have implemented BDD cucumber with serenity. But my serenity report is not coming properly. I'm expecting as number test cases  with failed and passed count with percentage.

@wakaleo Please refer the below dependencies i have added in build.gradle as well as my runner file.

Build.Gradle:
Page-1
![Screenshot (13)](https://user-images.githubusercontent.com/56257093/119023640-d21dea00-b9bf-11eb-9ce5-ad623119e697.png)

Page-2
![Screenshot (16)](https://user-images.githubusercontent.com/56257093/119023985-38a30800-b9c0-11eb-89e5-96606b1657af.png)
Runner class:
![Screenshot (15)](https://user-images.githubusercontent.com/56257093/119024071-52444f80-b9c0-11eb-9e6b-5aa1aa4ec4f4.png)
Report:
![Screenshot (18)](https://user-images.githubusercontent.com/56257093/119024700-01812680-b9c1-11eb-8fe0-ac42368e4ae5.png)

Expected Report layout:

![Screenshot (19)](https://user-images.githubusercontent.com/56257093/119025218-89673080-b9c1-11eb-85dd-5ea8d08cbd7c.png)

Thanks in advance!!!

**Comment by wakaleo** [comment]
Try with a more recent version: http://github.com/serenity-bdd/serenity-cucumber-starter

**Comment by anweshadhal** [comment]
Hi @wakaleo ,

Thanks for you quick response.

I have tried to replace the build.gradle with the one you have provided in the serenity-cucumber-starter project, but i'm getting the below error. Even i have imported the serenity-cucumber-starter project and saw the same error.

Script is running fine, with that error but reports are not coming as serenity report.(Same as i got before and raised this issue for.)

**Snapshot of error:**
![Screenshot (20)](https://user-images.githubusercontent.com/56257093/119134984-76a13a00-ba5b-11eb-885c-1ae21c8b9253.png)

**Comment by anweshadhal** [comment]
Thanks @wakaleo 

I'm able to run from command line and got the aggregate report as shown in the below snapshot of my project.

![Screenshot (21)](https://user-images.githubusercontent.com/56257093/119225290-83d42c80-bb20-11eb-896a-b29cb994b566.png)

**Comment by anweshadhal** [comment]
Getting repot as expected

**Comment by globalworming** [comment]
just out of curiosity @anweshadhal, why didn't you try a more recent version to begin with? For example if you found an old project on github or old documentation, we might want to update that.
