### ISSUE TITLE
feature marked as pending instead of success

### ISSUE THREAD

**Issue by dwursteisen** [serenity-bdd/serenity-cucumber#41]
To reproduce the issue: 

1. clone this [repository](https://github.com/dwursteisen/serenity-bug-report/tree/submodule), and checkout the branch ```submodule```.
1. ```mvn clean install``` on the root project (or from the module directory)
1. check the generated report (requirement tab)

The report should look like this : all tests in success except one in pending. (please note that is marked that 33% of tests are success instead of 50%)

![img](https://raw.githubusercontent.com/dwursteisen/serenity-bug-report/submodule/bug2.PNG)
 
__Expected__ : all tests are succed.

_workaround_: change, in the aa.feature file the line ```Fonctionnalité: AA scénario``` to match the file feature name. 

ie :  ```Fonctionnalité: AA scénario``` should be rewrite as ```Fonctionnalité: aa``` as it's in the ```aa.feature``` file.

**Comment by YamStranger** [comment]
Hello @dwursteisen

Thanks for this issue and provided test project!!

**Comment by cliviu** [comment]
Hi @dwursteisen 
 I think that we have a problem with  the feature name encoding. As workaround is not necessary to have the feature name the same as the file name but to use a feature name containing only plain ASCII characters. I will investigate the problem.

**Comment by cliviu** [comment]
hi @dwursteisen . have you tried with the latest version ?

**Comment by dwursteisen** [comment]
Not yet. 

I'm working on another project right now. But the next week, I think I'll have some time to test it.

**Comment by YamStranger** [comment]
It seems that this issue was fixed by @cliviu fix. Will close this ticket. 

Thanks!
