### ISSUE TITLE
Update serenity-core dependency

### ISSUE THREAD

**Issue by scotty6435** [serenity-bdd/serenity-cucumber#46]
The current release is dependent on serenity-core:1.1.25 which is absent from Maven repositories. As a result, including serenity-cucumber causes unresolved dependency errors requiring manual workarounds. Can you update to 1.1.26+?

**Comment by YamStranger** [comment]
Hello @scotty6435 
Sure ) 

Also please try to use jcentral in your gradle/mvn configs - here you can find all what you need.

**Comment by scotty6435** [comment]
I've excluded dependency resolution on this for now which prevents the error.

Is it safe to pull in a release candidate rather than the last stable version?

**Comment by YamStranger** [comment]
Hello @scotty6435, mostly it is better to use latest versions as it possible. 
Thanks!
