### ISSUE TITLE
cucumber-spring issue with Spring annotations

### ISSUE THREAD

**Issue by dkirrane** [serenity-bdd/serenity-cucumber#6]
Trying to use cucumber serenity but it doesn't pick up Spring beans defined using `org.springframework.context.annotation.Configuration` & `org.springframework.context.annotation.Bean`
```
@Configuration
public class AppConfig {
    @Bean
    public MyBean getMyBean() {
    }
}
```

**Comment by wakaleo** [comment]
Have you added the serenity-spring (
http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22serenity-spring%22)
dependency to your project?

On 6 March 2015 at 02:19, dkirrane <notifications@github.com> wrote:

> Trying to use cucumber serenity but it doesn't pick up Spring beans
> defined using org.springframework.context.annotation.Configuration &
> org.springframework.context.annotation.Bean
>
> @Configuration
> public class AppConfig {
>     @Bean
>     public MyBean getMyBean() {
>     }
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serenity-bdd/serenity-cucumber/issues/6>.
>



-- 
___________________________________________________
John Smart | Wakaleo Consulting  |  +61 407 247 642
Optimizing your software development process
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________

The dates for the 2014 BDD workshops have been scheduled! Check out our
upcoming *BDD/TDD Master classes*
<http://wakaleo.com/training/testing-and-tdd-for-java-developers> and
our *Advanced
BDD Requirements Workshops
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, coming
soon to *Sydney
<http://wakaleo.com/training/testing-and-tdd-for-java-developers/public-courses>
*
and *Melbourne
<http://wakaleo.com/training/testing-and-tdd-for-java-developers/public-courses>!*
___________________________________________________

**Comment by dkirrane** [comment]
Ah didn't know that existed. Thanks
