### ISSUE TITLE
Serenity reports are not displaying icons on jenkins setup on Ubuntu

### ISSUE THREAD

**Issue by heerqa** [serenity-bdd/serenity-cucumber#66]
<img width="1276" alt="screen shot 2016-07-29 at 11 40 23 pm" src="https://cloud.githubusercontent.com/assets/4687417/17258764/1073c4c0-55e6-11e6-869f-3ec05ab8399e.png">

The icons and pie chart is displaying correctly on laptop, but when running these test no ubuntu via jenkins the icons and pie chart is missing

**Comment by wakaleo** [comment]
As mentioned elsewhere, this is not a Serenity problem but rather a Jenkins configuration issue: see https://issues.jenkins-ci.org/browse/JENKINS-32026, https://wiki.jenkins-ci.org/display/JENKINS/Configuring+Content+Security+Policy and https://wiki.jenkins-ci.org/display/JENKINS/HTML+Publisher+Plugin.

**Comment by vikramvi** [comment]
@wakaleo  I follow below links to get this issue fixed but still can't see embedded images only in jenkis

1. https://stackoverflow.com/questions/34740963/missing-pie-chart-and-other-elements-when-display-serenity-report-from-jenkins

2. https://stackoverflow.com/questions/37618892/jenkins-content-security-policy

3. https://janmolak.com/serenity-with-jenkins-2-0-7f4b8d48efe9

![serenity_report_images_missing](https://user-images.githubusercontent.com/308490/36214677-659a335e-11aa-11e8-89a1-1647d336763e.png)

I'm not understanding what else may be going wrong, can you please have a quick look ?

**Comment by wakaleo** [comment]
Looks like something odd with your Serenity report archiving in Jenkins. Could be related to the Jenkins issue mentioned above.

**Comment by vikramvi** [comment]
I could get it fixed by running below in Jenkins

`System.setProperty("hudson.model.DirectoryBrowserSupport.CSP", "")
`
https://stackoverflow.com/questions/35783964/jenkins-html-publisher-plugin-no-css-is-displayed-when-report-is-viewed-in-j

Thanks for your time

**Comment by hirenshcybage** [comment]
Hello @wakaleo

Serenity reports are not displaying icons on jenkins setup on Linux
