### ISSUE TITLE
Serenity Cucumber: Mark manual tests as pass/fail 

### ISSUE THREAD

**Issue by yukyankee** [serenity-bdd/serenity-cucumber#68]
Hi,
I've got a quick question.
On the overall test results tab, is it possible to mark manual tests as pass or fail in feature files?
As far as I know, all those manual tests are categorized as Pending.
![image](https://cloud.githubusercontent.com/assets/6442564/18511814/1ede406e-7ab0-11e6-897e-a93606b42c7c.png)

Thank you,
Warit

**Comment by wakaleo** [comment]
At this stage, this isn't supported, though it maybe in the future. The thinking is that to mark a manual test as passing (or failing) could be misleading, as Serenity cannot know whether the version that was tested when you marked it as passing is the same as the one under test during any given test run.

**Comment by yukyankee** [comment]
@wakaleo Thank you for your quick response! My management team would be interested in this function. I couldn't agree with you more though.
