### ISSUE TITLE
The Serenity Steps are not skipped/ ignored if the feature is annotated with @wip 

### ISSUE THREAD

**Issue by ereticul** [serenity-bdd/serenity-cucumber#7]
Hi, 
I've executed a feature which is annotated with @wip tag and noticed that the Serenity steps are NOT ignored/ skipped (although Cucumber Steps are skipped).

I've played a little into the SerenityReporter and added the following statements checkForSkipped And checkForPending, as below and as a result the Serenity Steps would be marked as ignored. 
private void startScenario(Scenario scenario) {
        getThucydidesListeners().withDriver(ThucydidesWebDriverSupport.getDriver());
        StepEventBus.getEventBus().testStarted(scenario.getName());
        StepEventBus.getEventBus().addDescriptionToCurrentTest(scenario.getDescription());
           StepEventBus.getEventBus().addTagsToCurrentTest(convertCucumberTags(currentFeature.getTags()));
        StepEventBus.getEventBus().addTagsToCurrentTest(convertCucumberTags(scenario.getTags()));

        checkForSkipped(currentFeature);
        checkForPending(currentFeature);
    }

Maybe there is a better fix. Have a look.

Andy

**Comment by wakaleo** [comment]
Fixed in 1.0.12.

**Comment by ereticul** [comment]
Hi John,

Please execute this feature - simple_tagged_pending_feature.feature

You will be able to see that Serenity Step is NOT skipped, but on success actually:
@Step
    public void shouldBeBilled(int billedPrice, int totalPrice) {
        assertThat(billedPrice).isEqualTo(totalPrice);
    }

I noticed that into the StepEventBus.getEventBus().testStarted(scenario.getName()); there is clear(); so I suppose due to that it happens. So I fixed that added these both checks after events bus have been executed (as above) (and suppose it's NOT really in the right scope used but as workaround works fine for me):
checkForSkipped(currentFeature);
 checkForPending(currentFeature);

Just let you know.
Andy
