### ISSUE TITLE
Serenity Cucumber does not scan @Manual on feature level

### ISSUE THREAD

**Issue by yukyankee** [serenity-bdd/serenity-cucumber#70]
Hi,
In the document, it states that tagging a feature file @Manual on feature (story) level would consider all scenarios under the file manual scenarios.

> Generally, it is possible to use it to mark scenarios (@Manual on scenario level) or all scenarios in story (@manual on Story level).

However, from what I've tested, it seems the report does not properly recognize scenarios on a file with @Manual on top of the file as manual scenarios. The test steps are not skipped; and there is no humanoid icon for the manual scenario on the report. Could you introduce a fix for this issue?
The workaround is to tag @Manual above each scenario.
I'm using Serenity Cucumber version 1.1.11

**Comment by wakaleo** [comment]
Fixed in 1.1.26
