### ISSUE TITLE
Cucumber + Serenity serenity.use.unique.browser does not work 

### ISSUE THREAD

**Issue by derkoe** [serenity-bdd/serenity-cucumber#72]
When running Serenity with Cucumber then the serenity.use.unique.browser setting does not work - a browser (webdriver) is opened for each cucumber "Feature" (and closed after each "Feature").

**Comment by derkoe** [comment]
Anyone want's to merge this?

**Comment by jeromevdl** [comment]
Why the commit has not been merged on master ? 

Tests are already quite long to execute. So if in addition, the browser is killed each time, it's just too long.

I really need this or any other solution (as the intended property does not work).

**Comment by wakaleo** [comment]
See https://github.com/serenity-bdd/serenity-cucumber/pull/73

**Comment by jeromevdl** [comment]
Yes, I've seen it. In which version is it available?

By the way, maybe you could update the documentation http://thucydides.info/docs/serenity-staging/

> serenity.use.unique.browser
Set this to true for running all web tests in a single browser, for one test. Can be used for configuring Junit and Cucumber, default value is false.

> restart.browser.each.scenario
Set this to false for running all web tests in same story file with one browser, can be used when Jbehave is used. default value is false

**Comment by wakaleo** [comment]
It is available in the most recent version, from 1.2.x I believe.
