### ISSUE TITLE
Jira link in tests missing after 1.1.14

### ISSUE THREAD

**Issue by michaelgx** [serenity-bdd/serenity-cucumber#78]
The issue links in the tests in the serenity report to jira tickets are missing after version 1.1.14 even though the issue tag is present in the feature file.

serenityVersion=1.2.3-rc.3
serenityJiraVersion=1.1.3-rc.2
serenityCucumberVersion=1.1.23

**Comment by atulkumar93** [comment]
I'm also facing this issue.
I'm using following versions:

serenityVersion=1.2.3-rc.5
serenityJiraVersion=1.1.3-rc.2
serenityCucumberVersion=1.1.23

**Comment by michaelgx** [comment]
Workaround is to use version 1.1.14 of serenity Cucumber for now untill it is fixed

**Comment by atulkumar94** [comment]
I tried using following version:
serenityVersion=1.2.3-rc.5
serenityJiraVersion=1.1.3-rc.2
serenityCucumberVersion=1.1.14

Jira integration is working fine but getting below error when clicking on scenarios under test section:

Your file was not found
It may have been moved or deleted.
ERR_FILE_NOT_FOUND

**Comment by atulkumar93** [comment]
I tried using following version:
serenityVersion=1.2.3-rc.5
serenityJiraVersion=1.1.3-rc.2
serenityCucumberVersion=1.1.14

Jira integration is working fine but getting below error when clicking on scenarios under test section:

Your file was not found
It may have been moved or deleted.
ERR_FILE_NOT_FOUND

**Comment by wakaleo** [comment]
Try with Serenity Cucumber 1.1.23

**Comment by wakaleo** [comment]
I can't seem to reproduce this issue; it may be fixed by one of the other link-related fixes. Please check in version 1.1.23-rc.6 (available shortly)
