### ISSUE TITLE
Unable to use serenity-cucumber (aka thucydides-cucumber) along with cucumber-guice

### ISSUE THREAD

**Issue by grumblerchester** [serenity-bdd/serenity-cucumber#8]
I've created Cucumber test project and successfully configured Guice support by cucumber-guice. When I've added serenity-cucmber and configure test runner with CucumberWithSerenity I've got an error:
```sh
More than one Cucumber ObjectFactory was found in the classpath

You probably may have included, for instance, cucumber-spring AND cucumber-guice as part of
your dependencies. When this happens, Cucumber falls back to instantiating the
DefaultJavaObjectFactory implementation which doesn't provide IoC.
In order to enjoy IoC features, please remove the unnecessary dependencies from your class path.
```
The cause is there are two ObjectFactory implementations:
* cucumber.runtime.java.guice.impl.GuiceFactory (in cucumber-guice)
* cucumber.runtime.SerenityObjectFactory (in serenity-cucumber)

Is it possible to use serenity-cucumber along with cucumber guice?

**Comment by wakaleo** [comment]
Unfortunately not - Cucumber only allows one ObjectFactory and Serenity
needs its own.

On 12 March 2015 at 13:11, grumbler_chester <notifications@github.com>
wrote:

> I've created Cucumber test project and successfully configured Guice
> support by cucumber-guice. When I've added serenity-cucmber and configure
> test runner with CucumberWithSerenity I've got an error:
>
> More than one Cucumber ObjectFactory was found in the classpath
>
> You probably may have included, for instance, cucumber-spring AND cucumber-guice as part of
> your dependencies. When this happens, Cucumber falls back to instantiating the
> DefaultJavaObjectFactory implementation which doesn't provide IoC.In order to enjoy IoC features, please remove the unnecessary dependencies from your class path.
>
> The cause is there are two ObjectFactory implementations:
>
>    - cucumber.runtime.java.guice.impl.GuiceFactory (in cucumber-guice)
>    - cucumber.runtime.SerenityObjectFactory (in serenity-cucumber)
>
> Is it possible to use serenity-cucumber along with cucumber guice?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serenity-bdd/serenity-cucumber/issues/8>.
>



-- 
___________________________________________________
John Smart | Wakaleo Consulting  |  +61 407 247 642
Optimizing your software development process
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________

The dates for the 2014 BDD workshops have been scheduled! Check out our
upcoming *BDD/TDD Master classes*
<http://wakaleo.com/training/testing-and-tdd-for-java-developers> and
our *Advanced
BDD Requirements Workshops
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, coming
soon to *Sydney
<http://wakaleo.com/training/testing-and-tdd-for-java-developers/public-courses>
*
and *Melbourne
<http://wakaleo.com/training/testing-and-tdd-for-java-developers/public-courses>!*
___________________________________________________

**Comment by grumblerchester** [comment]
So... As I understand the same situation is with the cucumber-spring?
Is it possible to use cucumber + serenity-cucumber + any dependency injection library?

**Comment by wakaleo** [comment]
Serenity supports Spring integration - just add the serenity-spring module
to your classpath.

On 12 March 2015 at 13:52, grumbler_chester <notifications@github.com>
wrote:

> So... As I understand the same situation is with the cucumber-spring?
> Is it possible to use cucumber + serenity-cucumber + any dependency
> injection library?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serenity-bdd/serenity-cucumber/issues/8#issuecomment-78415016>
> .
>



-- 
___________________________________________________
John Smart | Wakaleo Consulting  |  +61 407 247 642
Optimizing your software development process
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________

The dates for the 2014 BDD workshops have been scheduled! Check out our
upcoming *BDD/TDD Master classes*
<http://wakaleo.com/training/testing-and-tdd-for-java-developers> and
our *Advanced
BDD Requirements Workshops
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, coming
soon to *Sydney
<http://wakaleo.com/training/testing-and-tdd-for-java-developers/public-courses>
*
and *Melbourne
<http://wakaleo.com/training/testing-and-tdd-for-java-developers/public-courses>!*
___________________________________________________

**Comment by ereticul** [comment]
John, 

Please correct me if I'm wrong, if I want to enjoy this trio "Cucumber-JVM + Spring Integration + Serenity-Cucumber" then I've to remove  the Cucumber-Spring dependency and add the "Serenity-Spring" dependency instead. Correct?

Thanks,
Andy

**Comment by grumblerchester** [comment]
@ereticul I've successfully configured project in that way.

**Comment by ArunPushparaj** [comment]
@grumblerchester  can you share some sample code with Spring Integration + Serenity-Cucumber.
