### ISSUE TITLE
Problems with tags when mixing cucumber and serenity tests

### ISSUE THREAD

**Issue by jeromevdl** [serenity-bdd/serenity-cucumber#83]
Hi,

I have different tests in my project. Some use the CucumberWithSerenity runner, some others (typically some smoke tests) simply use the SerenityRunner. 

When I want to execute a subset of the cucumber tests + the smoke tests, I use the tags as follow:

`mvn clean verify -Dcucumber.options="--tags @f17.05" -Dtags="smoke-test"`

The trouble is that I have the following error:

`None of the features at [src/test/resources/features] matched the filters: [@f17.05, @smoke-test]`

Although the feature files contain the tag @f17.05. As if cucumber was searching for a test which is tagged both by f17.05 and smoke-test, as if serenity called cucumber with the `--tags @f17.05 --tags @smoke-test` instead of `--tags @f17.05,@smoke-test` (AND instead of OR : https://github.com/cucumber/cucumber/wiki/Tags). Moreover, I did not ask cucumber to handle the tag smoke-test, it was a serenity tag...

Any idea of how I can achieve this ? Do I need to move all my tags from feature files to java (@WithTag) ? If this is not a bug, it is quite unlogical the way it handle the different tags...

Thanks

**Comment by wakaleo** [comment]
This is a known issue that will be fixed in the next release.
