### ISSUE TITLE
(Question not issue) Maven POM file out of date

### ISSUE THREAD

**Issue by dimitrisli** [serenity-bdd/serenity-cucumber#89]
hey guys,

just imported as Maven project and noticed that the POM file has the old namespace therefore compilation errors. I'm guessing Gradle is what used for this project.

Would it worth the while for me cleaning up the POM file?

thanks
Dimi

**Comment by wakaleo** [comment]
You mean the serenity-core project?

**Comment by dimitrisli** [comment]
I think serenity-core doesn't even have a POM xml file when I've imported it so Gradle is clearly the build/package option. I was referring to the serenity-cucumber project where an outdated POM exists.

**Comment by wakaleo** [comment]
Ok. The build and release process is Gradle-based now, so not a lot of point keeping the Pom.xml

**Comment by dimitrisli** [comment]
ok no problem, just checking
