### ISSUE TITLE
Incorrect order of displaying the example values in the Step Description

### ISSUE THREAD

**Issue by ereticul** [serenity-bdd/serenity-cucumber#9]
Hi,
Steps to reproduce:
(1) Execute the scenario outline below
  Scenario Outline: Buying lots of widgets
    Given I want to purchase <amount> widgets
    And a widget costs $<cost>
    When I buy the widgets
    Then I should be billed $<total>
  Examples:
  | amount | cost | total |
  | 0      | 10   | 0      |
  | 1      | 10   | 10    |
  | 2      | 10   | 50    |
  | 2      | 0     | 0      |

[Actual] The Step's Description would be as follow:
[1] {amount=0, total=0, cost=10} 
[1] {amount=1, total=10, cost=10} 
[1] {amount=2, total=50, cost=10} 
[1] {amount=2, total=0, cost=0}

[Expected]
The Step's Description would be as follow:
[1] {amount=0, cost=10, total=0} 
[1] {amount=1,  cost=10, total=10} 
[1] {amount=2, cost=10, total=50} 
[1] {amount=2, cost=0, total=0}

I've played into SerenityReporter and fixed that adding instead of Map<K,V> the LinkedHaspMap<K, V>

private List<Map<String, String>> getValuesFrom(List<ExamplesTableRow> examplesTableRows, List<String> headers) {

        List<Map<String, String>> rows = Lists.newArrayList();

        for (int row = 1; row < examplesTableRows.size(); row++) {
            LinkedHashMap<String, String> rowValues = Maps.newLinkedHashMap();
            int column = 0;
            for (String cellValue : examplesTableRows.get(row).getCells()) {
                String columnName = headers.get(column++);
                rowValues.put(columnName, cellValue);
            }
            rows.add(rowValues);
        }
        return rows;
    }

    private void addRow(List<Map<String, String>> exampleRows,
                        List<String> headers,
                        ExamplesTableRow currentTableRow) {
        LinkedHashMap<String, String> row = new LinkedHashMap<>();
        for (int j = 0; j < headers.size(); j++) {
            row.put(headers.get(j), currentTableRow.getCells().get(j));
        }
        exampleRows.add(row);
    }
I think the order is important due to that the Step Description should be right ordered with example's values when viewing the scenario outline in the Serenity Html Report. 

Thanks,
Andy

**Comment by wakaleo** [comment]
Thanks Andy, I'll put this into the next release.

On 12 March 2015 at 21:16, ereticul <notifications@github.com> wrote:

> Hi,
> Steps to reproduce:
> (1) Execute the scenario outline below
> Scenario Outline: Buying lots of widgets
> Given I want to purchase widgets
> And a widget costs $
> When I buy the widgets
> Then I should be billed $
> Examples:
> | amount | cost | total |
> | 0 | 10 | 0 |
> | 1 | 10 | 10 |
> | 2 | 10 | 50 |
> | 2 | 0 | 0 |
>
> [Actual] The Step's Description would be as follow:
> [1] {amount=0, total=0, cost=10}
> [1] {amount=1, total=10, cost=10}
> [1] {amount=2, total=50, cost=10}
> [1] {amount=2, total=0, cost=0}
>
> [Expected]
> The Step's Description would be as follow:
> [1] {amount=0, cost=10, total=0}
> [1] {amount=1, cost=10, total=10}
> [1] {amount=2, cost=10, total=50}
> [1] {amount=2, cost=0, total=0}
>
> I've played into SerenityReporter and fixed that adding instead of Map the
> LinkedHaspMap
>
> private List> getValuesFrom(List examplesTableRows, List headers) {
>
>     List<Map<String, String>> rows = Lists.newArrayList();
>
>     for (int row = 1; row < examplesTableRows.size(); row++) {
>         LinkedHashMap<String, String> rowValues = Maps.newLinkedHashMap();
>         int column = 0;
>         for (String cellValue : examplesTableRows.get(row).getCells()) {
>             String columnName = headers.get(column++);
>             rowValues.put(columnName, cellValue);
>         }
>         rows.add(rowValues);
>     }
>     return rows;
> }
>
> private void addRow(List<Map<String, String>> exampleRows,
>                     List<String> headers,
>                     ExamplesTableRow currentTableRow) {
>     LinkedHashMap<String, String> row = new LinkedHashMap<>();
>     for (int j = 0; j < headers.size(); j++) {
>         row.put(headers.get(j), currentTableRow.getCells().get(j));
>     }
>     exampleRows.add(row);
> }
>
> I think the order is important due to that the Step Description should be
> right ordered with example's values when viewing the scenario outline in
> the Serenity Html Report.
>
> Thanks,
> Andy
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serenity-bdd/serenity-cucumber/issues/9>.
>



-- 
___________________________________________________
John Smart | Wakaleo Consulting  |  +61 407 247 642
Optimizing your software development process
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________

The dates for the 2014 BDD workshops have been scheduled! Check out our
upcoming *BDD/TDD Master classes*
<http://wakaleo.com/training/testing-and-tdd-for-java-developers> and
our *Advanced
BDD Requirements Workshops
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, coming
soon to *Sydney
<http://wakaleo.com/training/testing-and-tdd-for-java-developers/public-courses>
*
and *Melbourne
<http://wakaleo.com/training/testing-and-tdd-for-java-developers/public-courses>!*
___________________________________________________

**Comment by ereticul** [comment]
Hi John,

My apologies, Have you a chance to put this in any release? Or just you're going to do...

May I ask please tell me how you consider that an issue can be closed? Is it there a Serenity workflow of defects principle?

Andy.

**Comment by wakaleo** [comment]
I'm testing it now...

**Comment by wakaleo** [comment]
Regarding the Serenity workflow for bug fixes, the best way if you have a proposed fix is to submit a pull request (which will get processed faster if there are unit tests that demonstrate the fix/new feature ;-) ).
