### ISSUE TITLE
unable to clear cookies and/or clean session with safari

### ISSUE THREAD

**Issue by rahulkulkarniyahoo** [serenity-bdd/serenity-cucumber#90]
Hello,

this is my first time here. In my setup, I am running my tests for CucumberWithSerenity.class
The issue is after execution of my tests with safari browser, safari does not clear the cookies and other related data. e.g. After login steps are completed, i have to search for a user and set the user so i get relevant sections. But safari retains the set user information from previous test execution. To address this issue, i have set the following in serenity.properties file : safari.options.useCleanSession=true
however, this does not seem to work.

On other browsers, i do not have such an issue. Is there a fix for this or am i implementing the property incorrectly?

**Comment by wakaleo** [comment]
Would you know how to do this in pure Selenium?

**Comment by rahulkulkarniyahoo** [comment]
Set up DesiredCapabilities and set values there. 
https://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/safari/SafariOptions.html

however since i am a newbie with implementing CucumberWithSerenity.class, wasnt sure where to address this topic. Have I written it incorrectly in the properties file?

I have begun using CucumberWithSerenity.class as it helps so much in cutting time coding time and seriously super easy to use.

**Comment by wakaleo** [comment]
You can use a custom driver for this, or in Serenity 1.6.10, you will be able to use the `safari.use.clean.session` property.
 (see https://github.com/serenity-bdd/serenity-core/commit/593ad9d4eb95e2e4c26487ffe672527aa0c7d178)
