### ISSUE TITLE
Incompatible types-  Found: CucumberWithSerenity.class, expected: org.junit.runner.Runner

### ISSUE THREAD

**Issue by Tech-D** [serenity-bdd/serenity-cucumber#91]
While defining **CucumberWithSerenity** test runner I get below error basically saying incompatible type. Has anyone encountered this issue?
_Incompatible types-  Found: CucumberWithSerenity.class, expected: org.junit.runner.Runner_

I am creating a simple serenity cucumber BDD automation test using maven on google website just to see how serenity works. Please advise if I am missing anything here.

ATTACHED - pom.xml and error screenshot

**Comment by wakaleo** [comment]
I can't see any attached files? The simplest way to create a sample project is to use the maven archetypes.

**Comment by Tech-D** [comment]
There is no issue with dependencies. I can see them downloaded successfully. The issue for me in the statement @RunWith(CucumberWithSerenity.class). 
import net.serenitybdd.cucumber.CucumberWithSerenity has been done as well.

![screenshot](https://user-images.githubusercontent.com/8907200/28647941-a35260fa-72ad-11e7-8bde-1a422caf3c04.jpg)

**Comment by Tech-D** [comment]
Apparently, there was some issue with **cucumber.api.junit** and **cucumber.api.java** jars that were downloaded. I had to delete and freshly download all jars to make it work. 

Thanks for the support!

**Comment by wakaleo** [comment]
Thanks for the update :-)
