### ISSUE TITLE
Property serenity.use.unique.browser does not work

### ISSUE THREAD

**Issue by learnappium** [serenity-bdd/serenity-cucumber#96]
I tried following . but still new browser is opening for each scenario

> serenity.use.unique.browser=true
> restart.browser.each.scenario = false
> thucydides.use.unique.browser = true 

```
<serenity.version>1.5.10</serenity.version> <!-- https://bintray.com/serenity/maven/serenity-core/ -->
        <serenity.maven.version>1.5.10</serenity.maven.version>
        <serenity.cucumber.version>1.5.7</serenity.cucumber.version> 
```

**Comment by wakaleo** [comment]
The `serenity.use.unique.browser` property is no longer used, use `restart.browser.for.each` instead, e.g. 

```
restart.browser.for.each = scenario
``` 

or 

```
restart.browser.for.each = feature
```

**Comment by learnappium** [comment]
Thanks @wakaleo
